# WEEK 2: Take Home Assignment
*Rushali Moteria*

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [2]:
import numpy as np



In [ ]:
A = np.array(['a', 'b', 'c'])
B = np.array(['d', 'e', 'f'])

#stacking vertically
C = np.vstack((A,B))
print(C)

D = np.hstack((A,B))
print(D)



[['a' 'b' 'c']
 ['d' 'e' 'f']]
['a' 'b' 'c' 'd' 'e' 'f']


In [ ]:
A = np.array([['a'], ['b'], ['c']])
B = np.array([['d'], ['e'], ['f']])

#stacking vertically
C = np.vstack((A,B))
print(C)

D = np.hstack((A,B))
print(D)

[['a']
 ['b']
 ['c']
 ['d']
 ['e']
 ['f']]
[['a' 'd']
 ['b' 'e']
 ['c' 'f']]


2. Find common elements between A and B.

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
C = np.intersect1d(A,B)
C


array([3, 4, 5])

3. Extract all numbers from A which are within a specific range. eg
between 5 and 10.

In [7]:
A = np.array([10,11,12,13,14,15])
indices = np.where((A >= 11) & (A <= 14))
print(A[indices])

[11 12 13 14]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0


In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# print(iris_2d)

indices = np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))
print(iris_2d[indices])


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Pandas Questions
5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).

In [14]:
import pandas as pd


In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

df2 = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]
df2



Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()
print(min_price_mean)
print(max_price_mean)

df['Min.Price'] = df['Min.Price'].fillna(min_price_mean)
df['Max.Price'] = df['Max.Price'].fillna(max_price_mean)

df.head()


17.118604651162787
21.45909090909091


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

7. How to get the rows of a dataframe with row sum > 100?

In [25]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

row_sums = df.sum(axis=1)

print(row_sums)

df2 = df[row_sums > 100]

df2

0      98
1     107
2     100
3     120
4     118
5     126
6      77
7      68
8      77
9      87
10     91
11    133
12     91
13    116
14     96
dtype: int64


0   1   2   3
1   38  26  25  18
3   29  33  28  30
4   31  38  20  29
5   35  19  36  36
11  38  27  37  31
13  39  39  28  10